name: Markdown Lint
on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  lintMarkdown:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Lint Markdown
        uses: avto-dev/markdown-lint@v1.3.1
        with:
          args: ./**/*.md
