name: Check markdown links
on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]
  schedule:
  - cron: '0 8 * * 0'
    
jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Link Checker
        uses: peter-evans/link-checker@v1
      - name: Create Issue From File
        uses: peter-evans/create-issue-from-file@v2
        with:
          title: Link Checker Report
          content-filepath: ./link-checker/out.md
          labels: report, automated issue
